export const strings = {
  app: { name: 'quit' },
  nav: {
    label: 'Navigation principale',
    home: 'Accueil',
    calendar: 'Calendrier',
    progress: 'Progression',
    history: 'Historique',
    settings: 'Réglages',
  },
  craving: { launch: 'Envie' },
  journal: {
    loading: 'Chargement…',
    error: 'Impossible de lire le journal sur cet appareil.',
  },
  quitMoment: {
    title: 'Depuis quand tu ne fumes plus ?',
    lead: 'Tout part de ce moment. Tu pourras le corriger plus tard.',
    now: 'Maintenant',
    or: 'ou',
    dateLabel: 'Une autre date et heure',
    submit: 'C’est depuis là',
    future: 'Ce moment n’est pas encore arrivé.',
    invalid: 'Indique une date et une heure complètes.',
  },
  streak: {
    region: 'Temps sans fumer',
    days: (count: number) => (count <= 1 ? 'jour sans fumer' : 'jours sans fumer'),
    step: (step: number, doseMg: number, daysToNext: number, targetMg: number) =>
      `Étape ${step} · ${doseMg} mg · J-${daysToNext} avant ${targetMg} mg`,
  },
  protocol: {
    title: 'Protocole',
    stepOf: (number: number, count: number) => `Étape ${number} / ${count}`,
    context: (number: number, doseMg: string) => `Étape ${number} · ${doseMg} mg`,
    /** The current step's dose, its brand when noted, then how long until what comes next. */
    detail: (doseMg: string, brand: string | undefined, remaining: string) =>
      [`${doseMg} mg`, brand, remaining].filter((part) => part !== undefined).join(' · '),
    day: (day: number, duration: number) => `Jour ${day} sur ${duration}`,
    untilNext: (days: number, doseMg: string) => `encore ${days} j avant ${doseMg} mg`,
    untilEnd: (days: number) => `encore ${days} j avant la fin`,
    over: 'Protocole terminé',
    overLead: 'Plus de patch à poser. Le streak, lui, continue.',
    edit: 'Modifier',
    back: 'Retour',
    lead: 'Chaque étape est un patch de 24 h. Tu peux tout changer, même en cours d’étape.',
    step: (number: number) => `Étape ${number}`,
    doseLabel: 'Dose (mg)',
    durationLabel: 'Durée (jours)',
    brandLabel: 'Marque (facultatif)',
    moveUp: (number: number) => `Monter l’étape ${number}`,
    moveDown: (number: number) => `Descendre l’étape ${number}`,
    remove: (number: number) => `Supprimer l’étape ${number}`,
    add: 'Ajouter une étape',
    save: 'Enregistrer',
    invalid: 'Chaque étape a besoin d’une dose et d’une durée en jours entiers.',
    empty: 'Garde au moins une étape.',
  },
  debug: {
    marker: 'Bac à sable',
    title: 'Bac à sable',
    lead: 'Ton vrai journal n’y est ni lu ni modifié.',
    shifts: 'Déplacer l’horloge',
    dayBack: '−1 j',
    hourBack: '−1 h',
    hourForward: '+1 h',
    dayForward: '+1 j',
    realTime: 'Revenir à l’heure réelle',
    wipe: 'Vider',
    leave: 'Sortir',
    close: 'Fermer',
  },
  multiplier: {
    label: 'Multiplicateur de streak',
    title: (current: number) => `Multiplicateur ×${current}`,
    next: (days: number, next: number) => `encore ${days} j pour ×${next}`,
    capped: 'au maximum',
  },
  level: {
    title: (level: number) => `Niveau ${level}`,
    label: (level: number) => `XP du niveau ${level}`,
    xp: (into: number, total: number) =>
      `${into.toLocaleString('fr-FR')} / ${total.toLocaleString('fr-FR')} XP`,
  },
  badges: {
    title: 'Badges',
    count: (unlocked: number, total: number) => `${unlocked} / ${total}`,
    locked: 'à débloquer',
  },
  design: {
    synthetic: 'Toutes les données sont fictives.',
    sections: {
      controls: 'Composants',
      colors: 'Couleurs',
      type: 'Typographie',
    },
    buttons: {
      primary: 'Poser le patch',
      secondary: 'Plus tard',
      outline: 'Modifier',
      ghost: 'Annuler',
      destructive: 'Supprimer ce fait',
      disabled: 'Indisponible',
    },
    switchLabel: 'Rappel du patch',
    segmentedLabel: 'Intensité de l’envie',
    segments: ['1', '2', '3'],
    sliderLabel: 'Humeur du check-in',
    tabsLabel: 'Période',
    tabs: ['Semaine', 'Mois', 'Tout'],
    tabsEmpty: 'Rien à afficher pour cette période.',
    drawer: {
      open: 'Ouvrir le tiroir',
      title: 'Poser le patch',
      body: 'Site suggéré : bras gauche. Le précédent était sur l’épaule droite.',
      confirm: 'C’est posé',
      cancel: 'Plus tard',
    },
    dialog: {
      open: 'Ouvrir la boîte de dialogue',
      title: 'Enregistrer un écart ?',
      body: 'Le streak et le multiplicateur repartent de zéro. Tes badges et tes jours sans fumer restent.',
      confirm: 'Enregistrer',
      cancel: 'Non, pas cette fois',
      close: 'Fermer',
    },
  },
} as const
