#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: quit on this VPS, behind the Cloudflare tunnel.
# Run from a checkout of the repo: sudo bash deploy/setup.sh. Safe to re-run: every stage
# keeps what an earlier run saved.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

DEPLOY_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
IMAGE=ghcr.io/maximespinard/quit:main
PUBLIC_HOST=quit.atelierspinard.com
CONFIG_DIR=/etc/quit
STATE=/var/lib/quit
TUNNEL_ENV=$CONFIG_DIR/tunnel.env
APP_ENV=$CONFIG_DIR/quit.env
COMPOSE=(docker compose --project-directory /opt/quit -f /opt/quit/compose.yaml)

# Listening TCP and UDP sockets on the host, one "proto address:port" per line.
listening() {
  { ss -Hltn | awk '{print "tcp " $4}'; ss -Hlun | awk '{print "udp " $4}'; } | sort -u
}

if [[ $EUID -ne 0 ]]; then
  printf '%sRun it as root: sudo bash %s%s\n' "$RED" "$0" "$RESET"
  exit 1
fi

banner "quit on this VPS"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Nothing changes on the system here. It checks the tools, then records the firewall rules and"
say "the listening ports, so the last stage can show they did not move."
missing=()
for tool in docker curl flock ss systemctl; do
  command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
done
docker compose version >/dev/null 2>&1 || missing+=("docker compose v2")
if (( ${#missing[@]} )); then
  warn "missing: ${missing[*]}"
  exit 1
fi
step "docker, compose, curl, flock, ss and systemctl are installed"
install -d -m 700 "$STATE" "$CONFIG_DIR"
if [[ -f $STATE/listening-before ]]; then
  note "firewall and ports recorded by an earlier run: kept as the reference"
else
  if command -v ufw >/dev/null 2>&1; then ufw status verbose >"$STATE/ufw-before" 2>&1 || true; fi
  listening >"$STATE/listening-before"
  step "recorded the firewall rules and the listening ports in $STATE"
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare tunnel token"
say "The tunnel 'quit' already exists in Cloudflare. Its token lets cloudflared on this VPS"
say "connect as that tunnel. It is written to $TUNNEL_ENV, readable by root only."
open_url "https://one.dash.cloudflare.com/"
step "Zero Trust → Networks → Tunnels → quit → Configure."
step "In the install command shown there, copy only the token: the long string after --token,"
step "starting with eyJ."
ENV_FILE=$TUNNEL_ENV
while :; do
  ask_secret TUNNEL_TOKEN "Paste the tunnel token (hidden):"
  [[ $TUNNEL_TOKEN =~ ^eyJ[A-Za-z0-9+/_=-]+$ ]] && break
  warn "That is not a tunnel token (one line of base64 starting with eyJ). Try again."
done
write_env TUNNEL_TOKEN "$TUNNEL_TOKEN"
chmod 600 "$TUNNEL_ENV"
unset TUNNEL_TOKEN
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Push keys (VAPID)"
say "The server signs its notifications with a VAPID key pair. It is made here, inside the"
say "image, and written to $APP_ENV without being shown. An existing pair is kept: a new one"
say "would silently break the phone's push subscription."
ENV_FILE=$APP_ENV
if [[ -n $(_existing VAPID_PRIVATE_KEY || true) ]]; then
  note "a key pair is already in $APP_ENV: kept"
else
  step "pulling $IMAGE"
  docker pull -q "$IMAGE" >/dev/null
  vapid_public="" vapid_private=""
  # --log-driver none: the private key is printed on the container's stdout, never logged.
  read -r vapid_public vapid_private < <(docker run --rm --log-driver none --entrypoint node "$IMAGE" -e \
    "const k = require('web-push').generateVAPIDKeys(); console.log(k.publicKey, k.privateKey)") || true
  if [[ -z $vapid_public || -z $vapid_private ]]; then
    warn "the key pair could not be generated; nothing was written"
    exit 1
  fi
  write_env VAPID_PUBLIC_KEY "$vapid_public"
  write_env VAPID_PRIVATE_KEY "$vapid_private"
  unset vapid_public vapid_private
fi
# Apple accepts an https:// contact: no email address leaves the VPS.
[[ -n $(_existing VAPID_SUBJECT || true) ]] || write_env VAPID_SUBJECT "https://$PUBLIC_HOST"
chmod 600 "$APP_ENV"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Install and start"
say "This copies the deploy files to root-owned places, starts the app, then the tunnel, and"
say "turns on the timer that deploys each new main image:"
note "  /opt/quit/compose.yaml and /opt/quit/update.sh"
note "  /etc/systemd/system/quit-update.service and quit-update.timer"
say "No port is published and the firewall is not touched."
confirm "Install and start quit now?" || { warn "stopped before installing; re-run when ready"; exit 1; }
install -d -m 755 /opt/quit
install -m 644 "$DEPLOY_DIR/compose.yaml" /opt/quit/compose.yaml
install -m 755 "$DEPLOY_DIR/update.sh" /opt/quit/update.sh
install -m 644 "$DEPLOY_DIR/quit-update.service" "$DEPLOY_DIR/quit-update.timer" /etc/systemd/system/
systemctl daemon-reload
step "files installed"
docker image rm quit:previous >/dev/null 2>&1 || true # the tag of an earlier update.sh
step "deploying the app (up to a minute)"
# update.sh exits 0 as well when there was nothing to deploy: --check says whether the app is up.
if ! /opt/quit/update.sh || ! /opt/quit/update.sh --check; then
  warn "the app did not pass its health check. Its last lines:"
  docker logs --tail 30 quit 2>&1 | sed 's/^/    /' || true
  exit 1
fi
# Waits for a deploy the timer may be running, so the two never recreate the app at once.
flock -w 300 "$STATE/update.lock" "${COMPOSE[@]}" up -d
step "app and tunnel running"
systemctl enable --now quit-update.timer >/dev/null 2>&1
step "timer on: each image CI publishes on main is live within about two minutes"
"${COMPOSE[@]}" ps
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify"
healthy=false
for _ in $(seq 1 15); do
  if curl -fsS -m 5 "https://$PUBLIC_HOST/api/health" >/dev/null 2>&1; then
    healthy=true
    break
  fi
  sleep 2
done
if $healthy; then
  step "https://$PUBLIC_HOST/api/health answers through the tunnel"
else
  warn "no answer from https://$PUBLIC_HOST yet. Tunnel logs: sudo docker logs quit-tunnel"
fi

new_sockets=$(comm -13 "$STATE/listening-before" <(listening))
if [[ -z $new_sockets ]]; then
  step "no new listening port on the host"
else
  warn "listening since the first run (quit publishes none; check these are yours):"
  printf '%s\n' "$new_sockets" | sed 's/^/    /'
fi

if [[ -f $STATE/ufw-before ]]; then
  if diff -q "$STATE/ufw-before" <(ufw status verbose 2>&1) >/dev/null; then
    step "ufw rules unchanged"
  else
    warn "ufw rules differ from the first run:"
    diff "$STATE/ufw-before" <(ufw status verbose 2>&1) | sed 's/^/    /' || true
  fi
fi

printf '\n'
say "Next, by hand:"
note "  install the app: open https://$PUBLIC_HOST in Safari → Share → Add to Home Screen"
note "  try a rollback once: sudo /opt/quit/update.sh --simulate-failure  (it must roll back)"
note "  device key, once the app can link (SYR-75): sudo docker exec quit node src/issue-device-key.ts"
pause "Press Enter to finish"

ENV_FILE="$CONFIG_DIR/ (tunnel.env, quit.env)" # the summary names one file; the values went to both
finish
