/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as LapseRouteImport } from './routes/lapse'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CravingPastRouteImport } from './routes/craving/past'
import { Route as CravingTimerRouteImport } from './routes/craving/timer'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as HistoryPositionRouteImport } from './routes/history/$position'
import { Route as PatchNewRouteImport } from './routes/patch/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const LapseRoute = LapseRouteImport.update({
  id: '/lapse',
  path: '/lapse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CravingPastRoute = CravingPastRouteImport.update({
  id: '/craving/past',
  path: '/craving/past',
  getParentRoute: () => rootRouteImport,
} as any)
const CravingTimerRoute = CravingTimerRouteImport.update({
  id: '/craving/timer',
  path: '/craving/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryPositionRoute = HistoryPositionRouteImport.update({
  id: '/history/$position',
  path: '/history/$position',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchNewRoute = PatchNewRouteImport.update({
  id: '/patch/new',
  path: '/patch/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/lapse': typeof LapseRoute
  '/protocol': typeof ProtocolRoute
  '/settings': typeof SettingsRoute
  '/craving/past': typeof CravingPastRoute
  '/craving/timer': typeof CravingTimerRoute
  '/history/$position': typeof HistoryPositionRoute
  '/patch/new': typeof PatchNewRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/lapse': typeof LapseRoute
  '/protocol': typeof ProtocolRoute
  '/settings': typeof SettingsRoute
  '/craving/past': typeof CravingPastRoute
  '/craving/timer': typeof CravingTimerRoute
  '/history/$position': typeof HistoryPositionRoute
  '/patch/new': typeof PatchNewRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/lapse': typeof LapseRoute
  '/protocol': typeof ProtocolRoute
  '/settings': typeof SettingsRoute
  '/craving/past': typeof CravingPastRoute
  '/craving/timer': typeof CravingTimerRoute
  '/history/$position': typeof HistoryPositionRoute
  '/patch/new': typeof PatchNewRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/lapse'
    | '/protocol'
    | '/settings'
    | '/craving/past'
    | '/craving/timer'
    | '/history/$position'
    | '/patch/new'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/lapse'
    | '/protocol'
    | '/settings'
    | '/craving/past'
    | '/craving/timer'
    | '/history/$position'
    | '/patch/new'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/lapse'
    | '/protocol'
    | '/settings'
    | '/craving/past'
    | '/craving/timer'
    | '/history/$position'
    | '/patch/new'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  LapseRoute: typeof LapseRoute
  ProtocolRoute: typeof ProtocolRoute
  SettingsRoute: typeof SettingsRoute
  CravingPastRoute: typeof CravingPastRoute
  CravingTimerRoute: typeof CravingTimerRoute
  HistoryPositionRoute: typeof HistoryPositionRoute
  PatchNewRoute: typeof PatchNewRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lapse': {
      id: '/lapse'
      path: '/lapse'
      fullPath: '/lapse'
      preLoaderRoute: typeof LapseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craving/past': {
      id: '/craving/past'
      path: '/craving/past'
      fullPath: '/craving/past'
      preLoaderRoute: typeof CravingPastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craving/timer': {
      id: '/craving/timer'
      path: '/craving/timer'
      fullPath: '/craving/timer'
      preLoaderRoute: typeof CravingTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$position': {
      id: '/history/$position'
      path: '/history/$position'
      fullPath: '/history/$position'
      preLoaderRoute: typeof HistoryPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patch/new': {
      id: '/patch/new'
      path: '/patch/new'
      fullPath: '/patch/new'
      preLoaderRoute: typeof PatchNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  LapseRoute: LapseRoute,
  ProtocolRoute: ProtocolRoute,
  SettingsRoute: SettingsRoute,
  CravingPastRoute: CravingPastRoute,
  CravingTimerRoute: CravingTimerRoute,
  HistoryPositionRoute: HistoryPositionRoute,
  PatchNewRoute: PatchNewRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
